server:
  port: 8080

spring:
  rabbitmq:
    host: localhost
    username: user
    password: password
    port: 5672
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/AuthBookingDb
    username: postgres
    password: Telefon310
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true