server:
  port: 80
spring:
  main:
    web-application-type: reactive
  cloud:
    gateway:
      globalcors:
      add-to-simple-url-handler-mapping: true
      cors-configurations:
      '[/**]':
        allowedOrigins: "*"
        allowedHeaders: "*"
        allowedMethods:
          - GET
          - POST

      default-filters:
        - RewritePath= /(?<segment>.*), /api/v1/$\{segment}
      routes:
        - id: auth-micro-service
          predicates:
            - Path=/auth/**
          uri: http://10.8.7.88:9090
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
            - name: CircuitBreaker
              args:
                name: auth
                fallbackUri: forward:/fallbackauth
        - id: user-micro-service
          predicates:
            - Path=/user/**
          uri: http://10.8.3.20:9093
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
            - name: CircuitBreaker
              args:
                name: auth
                fallbackUri: forward:/fallbackuser